# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sentiment.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sentiment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsentiment.proto\x12\x0csentiment.v1\"\x1e\n\x0ePredictRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"/\n\x0fPredictResponse\x12\r\n\x05label\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\"$\n\x13PredictBatchRequest\x12\r\n\x05texts\x18\x01 \x03(\t\"6\n\x14PredictBatchResponse\x12\x0e\n\x06labels\x18\x01 \x03(\t\x12\x0e\n\x06scores\x18\x02 \x03(\x01\"\r\n\x0bPingRequest\"\x1e\n\x0cPingResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xf0\x01\n\x10SentimentService\x12\x46\n\x07Predict\x12\x1c.sentiment.v1.PredictRequest\x1a\x1d.sentiment.v1.PredictResponse\x12U\n\x0cPredictBatch\x12!.sentiment.v1.PredictBatchRequest\x1a\".sentiment.v1.PredictBatchResponse\x12=\n\x04Ping\x12\x19.sentiment.v1.PingRequest\x1a\x1a.sentiment.v1.PingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sentiment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=33
  _globals['_PREDICTREQUEST']._serialized_end=63
  _globals['_PREDICTRESPONSE']._serialized_start=65
  _globals['_PREDICTRESPONSE']._serialized_end=112
  _globals['_PREDICTBATCHREQUEST']._serialized_start=114
  _globals['_PREDICTBATCHREQUEST']._serialized_end=150
  _globals['_PREDICTBATCHRESPONSE']._serialized_start=152
  _globals['_PREDICTBATCHRESPONSE']._serialized_end=206
  _globals['_PINGREQUEST']._serialized_start=208
  _globals['_PINGREQUEST']._serialized_end=221
  _globals['_PINGRESPONSE']._serialized_start=223
  _globals['_PINGRESPONSE']._serialized_end=253
  _globals['_SENTIMENTSERVICE']._serialized_start=256
  _globals['_SENTIMENTSERVICE']._serialized_end=496
# @@protoc_insertion_point(module_scope)
