[project]
name = "ml-backend"
version = "0.1.0"
description = "Servidor gRPC con BETO"
requires-python = ">=3.9"

dependencies = [
    "grpcio>=1.65.0",
    "grpcio-tools>=1.65.0",
    "transformers>=4.44.0"
    
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
